# Global LLM configuration (默认使用 DeepSeek)
[llm]
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"
api_key = ""  # 用你的新 DeepSeek API Key 替换这里
max_tokens = 4096
temperature = 0.7
api_type = "Openai"  # DeepSeek 使用 OpenAI 兼容 API
api_version = "2023-07-01"


# 备用 OpenAI GPT-4o 配置
[llm.openai]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = ""  # 替换为你的 OpenAI API Key
max_tokens = 4096
temperature = 0.7
api_type = "Openai"
api_version = "2023-07-01"

# 视觉模型（使用 GPT-4o）
[llm.vision]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = ""  # 替换为你的 OpenAI API Key
api_type = "Openai"
api_version = "2023-07-01"
